#!/usr/bin/env bash
set -euo pipefail

ENV_FILE="${ENV_FILE:-/etc/jetson-yolo-webui.env}"
SERVICE_NAME="${SERVICE_NAME:-jetson-yolo-webui.service}"
HOST_VALUE=""
PORT_VALUE=""
TOKEN_VALUE=""
CORS_VALUE=""
GENERATE_TOKEN=0
RESTART=1

usage() {
  cat <<'USAGE'
Usage:
  configure_access.sh [--host HOST] [--port PORT] [--generate-token | --token TOKEN] [--cors ORIGINS] [--no-restart]

Examples:
  sudo configure_access.sh --host 127.0.0.1 --generate-token
  sudo configure_access.sh --host 0.0.0.0 --generate-token --cors http://192.168.1.20:3000

Notes:
  - Non-loopback hosts require a token. If no token is supplied, one is generated.
  - The token is printed only when generated by this command.
USAGE
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --host)
      HOST_VALUE="${2:?missing --host value}"
      shift 2
      ;;
    --port)
      PORT_VALUE="${2:?missing --port value}"
      shift 2
      ;;
    --token)
      TOKEN_VALUE="${2:?missing --token value}"
      shift 2
      ;;
    --generate-token)
      GENERATE_TOKEN=1
      shift
      ;;
    --cors)
      CORS_VALUE="${2:?missing --cors value}"
      shift 2
      ;;
    --no-restart)
      RESTART=0
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1"
      usage
      exit 2
      ;;
  esac
done

if [ "$(id -u)" -ne 0 ] && [ "${ALLOW_NON_ROOT:-0}" != "1" ] && { [ ! -f "$ENV_FILE" ] || [ ! -w "$ENV_FILE" ]; }; then
  echo "Run with sudo or set ENV_FILE to a writable path."
  exit 1
fi

mkdir -p "$(dirname "$ENV_FILE")"
touch "$ENV_FILE"

get_env_key() {
  local key="$1"
  grep -E "^${key}=" "$ENV_FILE" 2>/dev/null | tail -1 | cut -d= -f2- || true
}

set_env_key() {
  local key="$1"
  local value="$2"
  local tmp
  tmp="$(mktemp)"
  awk -v key="$key" -v value="$value" '
    BEGIN { done = 0 }
    $0 ~ "^" key "=" {
      print key "=" value
      done = 1
      next
    }
    { print }
    END {
      if (!done) {
        print key "=" value
      }
    }
  ' "$ENV_FILE" > "$tmp"
  cat "$tmp" > "$ENV_FILE"
  rm -f "$tmp"
}

new_token() {
  python3 - <<'PY'
import secrets
print(secrets.token_urlsafe(32))
PY
}

is_non_loopback_host() {
  local host="$1"
  case "$host" in
    ""|"127.0.0.1"|"localhost"|"::1")
      return 1
      ;;
    127.*)
      return 1
      ;;
    *)
      return 0
      ;;
  esac
}

CURRENT_TOKEN="$(get_env_key JETSON_WEBUI_TOKEN)"
GENERATED_TOKEN=""

if [ "$GENERATE_TOKEN" = "1" ]; then
  TOKEN_VALUE="$(new_token)"
  GENERATED_TOKEN="$TOKEN_VALUE"
fi

if [ -n "$HOST_VALUE" ] && is_non_loopback_host "$HOST_VALUE" && [ -z "$TOKEN_VALUE" ] && [ -z "$CURRENT_TOKEN" ]; then
  TOKEN_VALUE="$(new_token)"
  GENERATED_TOKEN="$TOKEN_VALUE"
fi

if [ -n "$HOST_VALUE" ]; then
  set_env_key JETSON_WEBUI_HOST "$HOST_VALUE"
fi

if [ -n "$PORT_VALUE" ]; then
  set_env_key JETSON_WEBUI_PORT "$PORT_VALUE"
fi

if [ -n "$TOKEN_VALUE" ]; then
  set_env_key JETSON_WEBUI_TOKEN "$TOKEN_VALUE"
fi

if [ -n "$CORS_VALUE" ]; then
  set_env_key JETSON_WEBUI_CORS_ORIGIN "$CORS_VALUE"
fi

chmod 600 "$ENV_FILE" 2>/dev/null || true

if [ "$RESTART" = "1" ] && command -v systemctl >/dev/null 2>&1 && systemctl list-unit-files "$SERVICE_NAME" >/dev/null 2>&1; then
  systemctl restart "$SERVICE_NAME"
fi

echo "Updated $ENV_FILE"
echo "JETSON_WEBUI_HOST=$(get_env_key JETSON_WEBUI_HOST)"
echo "JETSON_WEBUI_PORT=$(get_env_key JETSON_WEBUI_PORT)"
if [ -n "$(get_env_key JETSON_WEBUI_TOKEN)" ]; then
  echo "JETSON_WEBUI_TOKEN_CONFIGURED=yes"
else
  echo "JETSON_WEBUI_TOKEN_CONFIGURED=no"
fi
echo "JETSON_WEBUI_CORS_ORIGIN=$(get_env_key JETSON_WEBUI_CORS_ORIGIN)"
if [ -n "$GENERATED_TOKEN" ]; then
  echo "GENERATED_JETSON_WEBUI_TOKEN=$GENERATED_TOKEN"
fi
